version: '3.6'

services:
  web:
    build: .
    ports:
     - "8080:8080"
    command: npm run start
    networks:
      - redis-net
    environment:
      - NODE_ENV=production
    depends_on:
      - redis
    volumes:
      - redis-data:/data
  redis:
    image: redis
    networks:
      - redis-net

networks:
  redis-net:

volumes:
  redis-data: