version: '3'

services:
  redis:
    build:
      context: .
      dockerfile: Dockerfile.redis
    container_name: cache
    expose:
      - 6379

  app:
    build:
      context: .
      dockerfile: Dockerfile
      args: 
        - PRODUCTION_SITE=${PRODUCTION_SITE:-https://www.myetherwallet.com}
        - GITHUB_SITE=${GITHUB_SITE:-https://api.github.com/repos/kvhnuke/etherwallet/contents?ref=gh-pages}
        - STATUS_SITE=${STATUS_SITE:-status.myetherwallet.com}
        - ALLOWED_IPS=${ALLOWED_IPS:-allowed-mew-ips.json}
    env_file: .env
    links:
      - redis
    environment:
      - REDIS_HOST=cache
    ports:
      - 8080:8080
    command: sh -c 'npm start'

