redis:
  image: redis
  container_name: cache
  expose:
    - 6379

app:
  build: ./
  links:
    - redis
  env_file:
    - .env
  environment:
    - REDIS_HOST=cache
  ports:
    - 8080:8080
  command: sh -c 'npm start'
