version: '3'

services:
  redis:
    image: redis
    container_name: cache
    expose:
      - 6379

  app:
    build:
      context: .
      dockerfile: Dockerfile
      args: 
        - PRODUCTION_SITE=$PRODUCTION_SITE
        - GITHUB_SITE=$GITHUB_SITE
        - STATUS_SITE=$STATUS_SITE
    env_file: .env
    links:
      - redis
    environment:
      - REDIS_HOST=cache
    ports:
      - 8080:8080
    command: sh -c 'npm start'
